{{- range $svc := list "authService" "employeeService" "payrollService" }}
{{- $config := index $.Values $svc }}
{{- if and $config.hpa $config.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $config.name }}-hpa
  namespace: {{ $.Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $config.name }}
  minReplicas: {{ $config.hpa.minReplicas }}
  maxReplicas: {{ $config.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.hpa.targetCPUUtilization }}
{{- end }}
{{- end }}
