spring:
  application:
    name: recruitment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr_recruitment
    username: nexushr
    password: nexushr_secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8087

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
