spring:
  application:
    name: attendance-service

  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr_attendance
    username: nexushr
    password: nexushr_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: false

server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.nexushr: DEBUG
